### ISSUE TITLE
Icon not centered with text on buttons

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [mcsiple/mmrefpoints#40]
![image](https://user-images.githubusercontent.com/47904621/118331745-db89ec80-b4bd-11eb-80b3-81bc4ba8ba90.png)

The gear and text are not center aligned in both the "Advanced" or "Solve for Bycatch" tabs. The "generate report" one looks fine!

**Comment by mcsiple** [comment]
I was able to adjust the button size and padding etc to get the button more centered... now it looks like this:
![Screen Shot 2021-06-14 at 2 51 25 PM](https://user-images.githubusercontent.com/2936426/121964193-0024ee80-cd20-11eb-8928-dd1f94440e43.png)

I am satisfied with this outcome! Fixed w commit 60de3191
