### ISSUE TITLE
Think about what you want exported objects to be

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [mcsiple/mmrefpoints#45]
I believe you are currently exporting all objects when you really only want to export functions or datasets you expect to be useful/reusable to those downloading your package.

I created a checklist below for reference so you can check them off as you remove from exports! One easy way to do this would be to go through the .Rd files in your `man/` folder and remove anything that does not have a corresponding documentation file as you seem to have documentation for all the functions you want to export.

- [ ] textOutput
- [ ] tabPanelBody
- [ ] includeHTML
- [ ] span
- [ ] h1
- [ ] dynamics
- [ ] runGitHub
- [ ] h2
- [ ] tagList
- [ ] tagHasAttribute
- [ ] h3
- [ ] HTML
- [ ] pmkey_en
- [ ] h4
- [ ] onBookmark
- [ ] fluidPage
- [ ] h5
- [ ] h6
- [ ] withTags
- [ ] polished_fr
- [ ] is.singleton
- [ ] removeTab
- [ ] fillRow
- [ ] showReactLog
- [ ] em
- [ ] updateNumericInput
- [ ] need
- [ ] tags
- [ ] golem_add_external_resources
- [ ] quoToFunction
- [ ] getUrlHash
- [ ] get_diff
- [ ] plotyears
- [ ] brushOpts
- [ ] pbrdefs_en
- [ ] onFlushed
- [ ] includeMarkdown
- [ ] withLogErrors
- [ ] bylevels_es
- [ ] showBookmarkUrlModal
- [ ] actionButton
- [ ] safeError
- [ ] pbrdefs_es
- [ ] clickOpts
- [ ] sidebarLayout
- [ ] column
- [ ] runTests
- [ ] downloadButton
- [ ] freezeReactiveValue
- [ ] onRestore
- [ ] splitLayout
- [ ] tagSetChildren
- [ ] navbarMenu
- [ ] bootstrapLib
- [ ] div
- [ ] rangenames_es
- [ ] serverInfo
- [ ] htmlTemplate
- [ ] callModule
- [ ] bindCache
- [ ] pageWithSidebar
- [ ] bylevels_fr
- [ ] pbrdefs_fr
- [ ] sliderInput
- [ ] inputPanel
- [ ] registerThemeDependency
- [ ] reactiveFileReader
- [ ] system.file
- [ ] rangenames_fr
- [ ] favicon
- [ ] get
- [ ] icon
- [ ] i18n
- [ ] dblclickOpts
- [ ] loadSupport
- [ ] onSessionEnded
- [ ] app_server
- [ ] tn_en
- [ ] fixedPanel
- [ ] with_golem_options
- [ ] brushedPoints
- [ ] mainPanel
- [ ] selectizeInput
- [ ] shinyServer
- [ ] flowLayout
- [ ] tn_es
- [ ] createWebDependency
- [ ] extractStackTrace
- [ ] runApp
- [ ] validate
- [ ] run_app
- [ ] hr
- [ ] invalidateLater
- [ ] %not_in%
- [ ] conditionalPanel
- [ ] includeText
- [ ] getfecmax
- [ ] ..stacktraceoff..
- [ ] tn_fr
- [ ] tn_en_adv
- [ ] renderPrint
- [ ] calc_z
- [ ] updateNavlistPanel
- [ ] modalButton
- [ ] runUrl
- [ ] absolutePanel
- [ ] checkboxInput
- [ ] tagAppendChild
- [ ] reactiveValues
- [ ] reactlog
- [ ] imageOutput
- [ ] reactiveTimer
- [ ] insertUI
- [ ] dateRangeInput
- [ ] rebuild_by_x
- [ ] drop_nulls
- [ ] throttle
- [ ] removeModal
- [ ] updateActionButton
- [ ] plot_proj
- [ ] uiOutput
- [ ] fillPage
- [ ] a
- [ ] tabPanel
- [ ] add_resource_path
- [ ] headerPanel
- [ ] debounce
- [ ] reactivePlot
- [ ] prob_rebuilt_goal
- [ ] reactiveValuesToList
- [ ] selectInput
- [ ] ns.sep
- [ ] with_devmode
- [ ] actionLink
- [ ] numericInput
- [ ] MockShinySession
- [ ] enableBookmarking
- [ ] registerInputHandler
- [ ] conditionStackTrace
- [ ] make_ptable
- [ ] multiplot_proj
- [ ] p
- [ ] display
- [ ] modalDialog
- [ ] plot_yield_curve
- [ ] logit
- [ ] undisplay
- [ ] updateCheckboxInput
- [ ] basicPage
- [ ] renderUI
- [ ] suppressDependencies
- [ ] setProgress
- [ ] updateVarSelectInput
- [ ] updateSelectizeInput
- [ ] hideTab
- [ ] getShinyOption
- [ ] renderTable
- [ ] urlModal
- [ ] tn_es_adv
- [ ] thumbnail_label2
- [ ] updateDateInput
- [ ] printError
- [ ] reactivePoll
- [ ] runGist
- [ ] reactiveText
- [ ] devmode
- [ ] hoverOpts
- [ ] showModal
- [ ] plot_pinnipeds
- [ ] shinyOptions
- [ ] passwordInput
- [ ] get_golem_config
- [ ] req
- [ ] downloadLink
- [ ] httpResponse
- [ ] shinyAppTemplate
- [ ] wellPanel
- [ ] rvtl
- [ ] onReactiveDomainEnded
- [ ] bookmarkButton
- [ ] list_to_li
- [ ] tagAppendChildren
- [ ] markdown
- [ ] projections
- [ ] ..stacktraceon..
- [ ] exportTestValues
- [ ] restoreInput
- [ ] get_rf
- [ ] isolate
- [ ] isTruthy
- [ ] get_devmode_option
- [ ] bylevels_en
- [ ] snapshotPreprocessOutput
- [ ] onBookmarked
- [ ] isRunning
- [ ] updateVarSelectizeInput
- [ ] maskReactiveContext
- [ ] includeScript
- [ ] removeInputHandler
- [ ] updateCheckboxGroupInput
- [ ] key_missing
- [ ] makeReactiveBinding
- [ ] pre
- [ ] rangenames_en
- [ ] fileInput
- [ ] pop_vs_yield
- [ ] fixedPage
- [ ] app_ui
- [ ] renderText
- [ ] reactiveVal
- [ ] renderImage
- [ ] tableOutput
- [ ] onRestored
- [ ] shinyApp
- [ ] outputOptions
- [ ] shinyAppFile
- [ ] markRenderFunction
- [ ] colorscheme
- [ ] onStop
- [ ] updateTextInput
- [ ] exprToFunction
- [ ] browserViewer
- [ ] splash_fr
- [ ] updateTextAreaInput
- [ ] is.key_missing
- [ ] dataTableOutput
- [ ] library.dynam.unload
- [ ] reactivePrint
- [ ] find_msyr
- [ ] removeUI
- [ ] not_na
- [ ] abund_rel_vec
- [ ] tagGetAttribute
- [ ] reactive
- [ ] ggradar
- [ ] shinyAppDir
- [ ] removeResourcePath
- [ ] splash_es
- [ ] fixedRow
- [ ] runGadget
- [ ] textInput
- [ ] bindEvent
- [ ] jumbotron2
- [ ] getDefaultReactiveDomain
- [ ] updateSelectInput
- [ ] fluidRow
- [ ] col_10
- [ ] diskCache
- [ ] col_12
- [ ] sizeGrowthRatio
- [ ] updateSliderInput
- [ ] stopApp
- [ ] named_to_li
- [ ] freezeReactiveVal
- [ ] observe
- [ ] updateDateRangeInput
- [ ] get_f
- [ ] renderCachedPlot
- [ ] eventReactive
- [ ] setSerializer
- [ ] bootstrapPage
- [ ] Progress
- [ ] tag
- [ ] splash_en
- [ ] withMathJax
- [ ] rv
- [ ] sidebarPanel
- [ ] submitButton
- [ ] list_to_p
- [ ] withProgress
- [ ] reactlogShow
- [ ] includeCSS
- [ ] animationOptions
- [ ] insertTab
- [ ] reactiveUI
- [ ] app_sys
- [ ] removeNotification
- [ ] helpText
- [ ] getQueryString
- [ ] reactlogReset
- [ ] varSelectInput
- [ ] code
- [ ] is.reactivevalues
- [ ] updateTabsetPanel
- [ ] tn_fr_adv
- [ ] tabsetPanel
- [ ] plot
- [ ] dialogViewer
- [ ] downloadHandler
- [ ] addResourcePath
- [ ] %\|NA\|%
- [ ] is.shiny.appobj
- [ ] central
- [ ] tagAppendAttributes
- [ ] observeEvent
- [ ] col_1
- [ ] col_2
- [ ] with_red_star
- [ ] col_3
- [ ] verticalLayout
- [ ] htmlOutput
- [ ] col_4
- [ ] col_6
- [ ] strong
- [ ] incProgress
- [ ] col_8
- [ ] snapshotExclude
- [ ] activate_js
- [ ] installExprFunction
- [ ] get_mnpl
- [ ] updateActionLink
- [ ] as.shiny.appobj
- [ ] showTab
- [ ] prependTab
- [ ] moduleServer
- [ ] plotOutput
- [ ] navbarPage
- [ ] reactiveTable
- [ ] get_dz
- [ ] updateQueryString
- [ ] setBookmarkExclude
- [ ] titlePanel
- [ ] showNotification
- [ ] dateInput
- [ ] enurl
- [ ] tagRemoveAttributes
- [ ] %\|\|%
- [ ] conditionStackTrace<-
- [ ] inv_logit
- [ ] createRenderFunction
- [ ] onFlush
- [ ] navlistPanel
- [ ] repeatable
- [ ] formatStackTrace
- [ ] varSelectizeInput
- [ ] parseQueryString
- [ ] plotPNG
- [ ] testServer
- [ ] pmkey_fr
- [ ] updateRadioButtons
- [ ] NS
- [ ] in_devmode
- [ ] printStackTrace
- [ ] renderDataTable
- [ ] shinyUI
- [ ] abund_rel
- [ ] paneViewer
- [ ] radioButtons
- [ ] npr
- [ ] nyears
- [ ] br
- [ ] appendTab
- [ ] memoryCache
- [ ] jq_hide
- [ ] ce
- [ ] singleton
- [ ] getCurrentOutputInfo
- [ ] resourcePaths
- [ ] pmkey_es
- [ ] rep_br
- [ ] captureStackTraces
- [ ] nyears.simple
- [ ] add_trans
- [ ] is.reactive
- [ ] getCurrentTheme
- [ ] verbatimTextOutput
- [ ] plot_bycatch_guesses
- [ ] snapshotPreprocessInput
- [ ] updateNavbarPage
- [ ] reactiveConsole
- [ ] fillCol
- [ ] not_null
- [ ] checkboxGroupInput
- [ ] polished_en
- [ ] runExample
- [ ] cat
- [ ] polished_es
- [ ] withReactiveDomain
- [ ] nearPoints
- [ ] validateCssUnit
- [ ] renderPlot
- [ ] textAreaInput
- [ ] img
- [ ] bundle_resources

**Comment by mcsiple** [comment]
I don't know exactly where it happened, but after making several changes to the NAMESPACE to simplify dependencies, etc, I don't have all of these in the exports anymore:

```
> getNamespaceExports("mmrefpoints")
 [1] "plot_bycatch_guesses" "run_app"              "abund_rel_vec"        "get_f"                "add_trans"           
 [6] "dynamics"             "get_mnpl"             "find_msyr"            "plot_pinnipeds"       "npr"                 
[11] "plot_yield_curve"     "get_rf"               "calc_z"               "get_dz"               "prob_rebuilt_goal"   
[16] "ce"                   "inv_logit"            "rebuild_by_x"         "plot_proj"            "pop_vs_yield"        
[21] "projections"          "make_ptable"          "multiplot_proj"       "logit"                "abund_rel"           
[26] "getfecmax"            "get_diff"             "ggradar"
```

I am going to mark this as closed since these are all functions included in the package -- but I wish I had gotten to use this checklist because I love checklists.
